### ISSUE TITLE
Use python module for urbandictionary lookups

### ISSUE THREAD

**Issue by justingood** [justingood/terribot#36]
Will be cleaner than scraping the page. Will return data that's easier to work with, too.

https://pypi.python.org/pypi/helga-urbandictionary
or
https://pypi.python.org/pypi/py-urbandict/0.1

**Comment by justingood** [comment]
Or just use the [API](https://github.com/mvrilo/urban)

**Comment by jeffmurchison** [comment]
We used the API before, actually.

**Comment by justingood** [comment]
Ah yes you're right, my bad. I blame code complexity.
Let's look at http://docs.python-requests.org/en/latest/ instead of urllib. It's much easier to use.

**Comment by jeffmurchison** [comment]
Yeah, I'm not sure where I got that example code when I added it initially but it is messy. 

Should we re-enable it in the meantime though?

**Comment by justingood** [comment]
It actually doesn't work under python3 :cry: 

urllib had some changes, so I opted to fix it later. Feel free to take a stab at it, if you have time to spare.

**Comment by justingood** [comment]
Working using the requests module currently, but it still needs
* the carriage returns stripped out
* return a negative result (can't find definition)

And then we should be back at feature parity with the old one

**Comment by justingood** [comment]
This is working half decent for now. If we care enough, we can just go ahead and fix it. The code is much cleaner than before.
