### ISSUE TITLE
Rewrite pytg for newer Telegram CLI

### ISSUE THREAD

**Issue by justingood** [justingood/terribot#43]
Might not even be possible, but it looks like the official client now supports Lua:
https://github.com/vysheng/tg/blob/master/README-LUA

Using the mainline client would enable us to use the updated functionality and probably fix some of the weird crashes the bot currently experiences on the forked client version we're using.

**Comment by luckydonald** [comment]
I took over maintainance, pytg got updated.  [pytg](https://github.com/luckydonald/pytg) (https://github.com/luckydonald/pytg/issues/19)

**Comment by justingood** [comment]
Saw that, already using your update :smile: 
Thanks a lot!
