### ISSUE TITLE
Mark messages as read after acting on them

### ISSUE THREAD

**Issue by justingood** [justingood/terribot#52]
Otherwise starting up somewhere else will act on everything...

**Comment by luckydonald** [comment]
But, in groups you don't know any longer, if someone actually read them messages, or if just the bot did.

**Comment by justingood** [comment]
Ah, good point.

I was mistaken, and thought this was from the bot's standpoint, ie: if a second bot & telegram client spins up, it will act on all of the recent messages again, not knowing they have already been processed by another instance of the bot.

I'll have to see if there's a way to avoid showing old messages when starting up *tg*...

**Comment by luckydonald** [comment]
There was a `backlog` feature, separating already proceeded messages, but as far as I could follow discussions, that cli feature is broken now...

**Comment by justingood** [comment]
That's too bad. I suppose there's nothing to be done unless they decide to add that functionality :-(
